name: Build Debug APK

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create local.properties
      env:
        AD_APP_ID: ${{ secrets.AD_APP_ID }}
        AD_MAIN_ACTIVITY_INTERSTITIAL: ${{ secrets.AD_MAIN_ACTIVITY_INTERSTITIAL }}
        AD_DEVICE_LIST_BANNER_1: ${{ secrets.AD_DEVICE_LIST_BANNER_1 }}
        AD_DEVICE_LIST_BANNER_2: ${{ secrets.AD_DEVICE_LIST_BANNER_2 }}
      run: |
        echo "AD_APP_ID=$AD_APP_ID" > local.properties
        echo "AD_MAIN_ACTIVITY_INTERSTITIAL=$AD_MAIN_ACTIVITY_INTERSTITIAL" >> local.properties
        echo "AD_DEVICE_LIST_BANNER_1=$AD_DEVICE_LIST_BANNER_1" >> local.properties
        echo "AD_DEVICE_LIST_BANNER_2=$AD_DEVICE_LIST_BANNER_2" >> local.properties

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-sdk-version: 30
        components: build-tools;30.0.2,platform-tools,android-30

    - name: Build project
      run: ./gradlew build

    - name: Test project
      run: ./gradlew test

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Delete local.properties
      run:  rm -f local.properties

    - name: Push APK
      uses: actions/upload-artifact@v3
      with:
        name: app.apk
        path: app/build/outputs/apk/debug/app-debug.apk
