name: Build and Test for Dev

on:
  push:
    branches:
    - '*DEV*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Android Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create local.properties
      run: |
        echo "AD_MAIN_ACTIVITY_INTERSTITIAL=ca-app-pub-3940256099942544/1033173712" > local.properties

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-sdk-version: 30
        components: build-tools;30.0.2,platform-tools,android-30

    - name: Build project
      run: ./gradlew build

    - name: Test project
      run: ./gradlew test
