name: Create local.properties for testing
on:
  workflow_dispatch:

jobs:
  create-local-properties-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create local.properties
        run: |
          echo "AD_MAIN_ACTIVITY_INTERSTITIAL=ca-app-pub-3940256099942544/1033173712" > local.properties